spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: QueroTrabalhar

  profiles:
    # Se a variavel de ambiente nao existir, o perfil 'test' sera ativado por padrao
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2-console

# Configuracoes de Seguranca JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

google:
  maps:
    api:
      url: ${GOOGLE_MAPS_API_URL}
      path: ${GOOGLE_MAPS_API_PATH}
      key: ${GOOGLE_MAPS_API_KEY}